services:
  auto-novel:
    container_name: auto-novel
    build:
      context: ./web
    image: auto-novel:beta
    ports:
      - 8011:80
    volumes:
      - ./web/config:/root/.config/auto-novel
    restart: unless-stopped
